apiVersion: apps/v1
kind: Deployment
metadata:
 name: movieswebapp
 labels:
    app: movieswebapp
spec:
 replicas: 2
 selector:
    matchLabels:
      app: movieswebapp
 template:
    metadata:
       labels:
        app: movieswebapp
    spec:
      containers:
      - name: movieswebappservice
        image: us.icr.io/ibmperumf2/movieswebappimg
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
 name: movieswebapp
spec:
 type: NodePort
 selector:
   app: movieswebapp
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32083
 selector:
   app: movieswebapp